// The wire contract of the createBooking Server Action: what the client sends,
// and the discriminated union it gets back.
//
// These live in their own module because `bookings.ts` carries the `'use server'`
// directive, and such a module may only export async functions. Types are erased
// at compile time, so they are re-exported from there for convenience —
// importing them from either path is identical.
//
// `field` reuses BookingFailureField from booking.ts rather than declaring a
// parallel list of field names. Two hand-maintained copies of the same six
// strings is exactly how a server that reports 'slot' ends up talking to a UI
// that only knows 'timeSlot'.

import type { BookingFailureField } from '@/lib/booking';

/**
 * Why a field was rejected — finer-grained than `field` alone, since 'date' can
 * fail three different ways. Machine-readable on purpose: the Thai copy lives in
 * `submitFailureMessage()` in booking.ts, so this must stay codes, not sentences.
 */
export type ValidationReason =
  | 'malformed'
  | 'out_of_window'
  | 'closed'
  | 'unknown_slot'
  | 'past'
  | 'out_of_range'
  | 'empty'
  | 'invalid_format'
  | 'too_long';

/**
 * What the client submits.
 *
 * `date` is a 'YYYY-MM-DD' calendar date in Asia/Bangkok — NOT an index into the
 * rendered date list, and not a serialised Date. An index would be impossible to
 * re-validate, since the server would have to trust the client's idea of which
 * dates were on offer; a Date would arrive as an instant whose Bangkok calendar
 * day depends on how it was built.
 *
 * Every field is re-validated server-side regardless of these types. A Server
 * Action is a public POST endpoint, so the declared shape is a convenience for
 * the caller and never a guarantee about what actually arrives.
 */
export interface CreateBookingInput {
  date: string;
  /** 'HH:mm', one of TIME_SLOTS. */
  slot: string;
  partySize: number;
  name: string;
  phone: string;
  /** Empty string when the customer left the note blank; stored as SQL NULL. */
  note: string;
}

/**
 * The outcome of a booking attempt.
 *
 * There is deliberately NO variant for "the database broke". An unexpected
 * failure throws instead, which the client adapter already turns into its
 * `unreachable` failure — that keeps this union to the four outcomes that are
 * genuinely part of the booking domain, and keeps the consumer's switch
 * exhaustive over them.
 *
 * `slot-just-filled` is ordinary control flow, not an error: there are no
 * temporary seat holds by design, so a slot legitimately can fill while a
 * customer is still filling in the form. `seatsRemaining` says what is actually
 * left — possibly 0 — so the UI can explain the situation rather than just
 * refusing.
 */
export type CreateBookingResult =
  | {
      status: 'success';
      /** Generated by the database (a sequence), so it cannot collide. */
      reference: string;
      seatsRemaining: number;
    }
  | { status: 'slot-just-filled'; seatsRemaining: number }
  | {
      status: 'rate-limited';
      /** Which limit tripped: too many attempts from this IP, or too many bookings on this phone today. */
      scope: 'ip' | 'phone';
      /** Seconds until the IP limit's rolling window frees a slot. Always null for the per-phone daily limit. */
      retryAfterSeconds: number | null;
    }
  | {
      status: 'validation-failed';
      field: BookingFailureField;
      reason: ValidationReason;
    };
